# Generated by Django 5.2.6 on 2025-10-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_general', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='color',
        ),
    ]
