# Generated by Django 5.2.6 on 2025-09-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_pedido',
            field=models.CharField(choices=[('cliente', 'Pedido de Cliente'), ('insumo', 'Solicitud de Insumo')], default='cliente', max_length=10),
        ),
    ]
