# Generated by Django 5.2.6 on 2025-11-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Descuento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total_final',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Final'),
        ),
    ]
