# Generated by Django 5.2.6 on 2025-11-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_general', '0002_pedido_descuento_pedido_total_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tiene_email',
            field=models.BooleanField(default=False, editable=False, verbose_name='Email Registrado'),
        ),
    ]
