# Generated by Django 5.2.6 on 2025-11-07 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_general', '0003_cliente_tiene_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total_final',
        ),
    ]
