# Generated by Django 5.2.6 on 2025-11-09 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_general', '0005_pedido_descuento_pedido_total_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='tiene_email',
        ),
    ]
